apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: default
  labels:
    app: webapi
spec:
  selector:
    app: webapi
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
    
      